# Generated by Django 3.2.6 on 2021-08-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_integeranswer_submission_textanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_answers', to='core.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_answers', to='core.submission')),
            ],
            options={
                'default_related_name': 'number_answers',
            },
        ),
        migrations.DeleteModel(
            name='IntegerAnswer',
        ),
    ]
