# Generated by Django 3.2.6 on 2021-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_form_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
