# Generated by Django 3.2.6 on 2021-08-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_form_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='creation_date',
        ),
    ]
