# Generated by Django 3.2.6 on 2021-08-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_question_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text')], default='text', max_length=8),
        ),
    ]
